### ISSUE TITLE
Conflict with Bourbon

### ISSUE THREAD

**Issue by seifsallam** [polikin/animate.sass#2]
I'm using Bourbon in addition to animate.css, but my project doesn't compile because i'm using `transform` mixin by bourbon, but it is trying to use animate.scss. 

So i was thinking maybe we can add namespace to all animate.scss mixins because i believe its only used locally.

If its ok, i can open a PR to fix that issue

**Comment by polikin** [comment]
Can you show a code sample. Because you can't use animation on your element if you already have a transform.

**Comment by seifsallam** [comment]
Here, I'm not sure if i understand what you mean

``` scss
.alertify-hidden {
  @include transform(scale($alertify-scale-size));
}
```

**Comment by polikin** [comment]
if you want to add an animation on `.alertify-hidden`, wrap you div into another one.

ex:

```
<div class="animated flipInX">
    <div class="alertify-hidden"></div>
</div>
```

**Comment by seifsallam** [comment]
thats not the problem. In bourbon, there is already existing mixin that handles the transformation. Calling `transform` here calls animate.css transform mixin, which takes different parameters and build fails, and i'm not actually trying to use animate.css transition mixin, i'm trying to use bourbon.

**Comment by polikin** [comment]
Sorry about that, Well, I don't have objection with modify the transform mixin if it can help to works with compass & bourbon.

**Comment by seifsallam** [comment]
cool, is it ok to change the other mixins too, to avoid this behavior anywhere else?

**Comment by polikin** [comment]
So, I did something quick. I changed `@mixin transform` & `@mixin transform-origin` to `@mixin transform-animate` & `@mixin transform-origin-animate`

**Comment by seifsallam** [comment]
What do you think about `@mixin an-transform` & `@mixin an-transform-origin`?

**Comment by polikin** [comment]
I think that `an` is not that clear. I can add `animate` as a suffix.

`@mixin animate-transform` & `@mixin animate-transform-origin`?

**Comment by seifsallam** [comment]
Awesome :)

**Comment by polikin** [comment]
Done!

**Comment by seifsallam** [comment]
Thanks a lot :)

**Comment by polikin** [comment]
No prob. Drop me a line if you have any bugs.

## Regards,

**Comment by seifsallam** [comment]
There is still conflict with `animation` mixin

**Comment by polikin** [comment]
Fixed

**Comment by seifsallam** [comment]
thanks again, but you please update `core` too
